---
# main task file

- name: ensure download folder
  file:
    path: "{{ jail_template_download }}"
    state: directory

- name: ensure release downloaded
  get_url:
    url: "{{ freebsd_downloadsite }}/{{ jail_release }}/{{ item.file }}"
    dest: "{{ jail_template_download }}/{{ item.file }}"
  with_items: "{{ jail_default_install }}"

- name: setup dataset
  include_role:
    name: bvansomeren.zfs
    tasks_from: dataset
  vars:
    zfs_dataset:
      name: "{{ jail_dataset }}"
      extra_zfs_properties:
        mountpoint: "{{ jail_location }}"

- name: ensure jail.conf contains global settings
  blockinfile:
    dest: /etc/jail.conf
    create: yes
    insertbefore: BOF
    marker: "# {mark} Global settings applied to all jails."
    content: |
        {% for opt in jail_default_opts %}
        {{ opt.name }}{% if opt.option is defined %} = "{{ opt.option }}"{% endif %};
        {% endfor %}

- name: enable jails in rc.conf
  command: sysrc jail_enable="YES"
  register: sysrc_changed
  changed_when:  "'YES -> YES' not in sysrc_changed.stdout"

- name: enable parallel jail start in rc.conf
  command: sysrc jail_parallel_start="YES"
  when: jail_parallel_start
  register: sysrc_changed
  changed_when:  "'YES -> YES' not in sysrc_changed.stdout"
